import React from 'react'
import './App.css'
import Card from './components/Card';

const users = [
  {
    id: 1,
    company: "Amazon",
    logo: "https://logo.clearbit.com/amazon.com",
    posted: "5 days ago",
    role: "Senior UI/UX Designer",
    type: "Part-Time",
    level: "Senior Level",
    salary: "$120/hr",
    location: "Mumbai, India",
  },
  {
    id: 2,
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    posted: "2 days ago",
    role: "Frontend Developer",
    type: "Full-Time",
    level: "Mid Level",
    salary: "$100/hr",
    location: "Bangalore, India",
  },
  {
    id: 3,
    company: "Microsoft",
    logo: "https://logo.clearbit.com/microsoft.com",
    posted: "1 day ago",
    role: "React Developer",
    type: "Remote",
    level: "Junior Level",
    salary: "$90/hr",
    location: "Hyderabad, India",
  },
  {
    id: 4,
    company: "Netflix",
    logo: "https://logo.clearbit.com/netflix.com",
    posted: "3 days ago",
    role: "Product Designer",
    type: "Full-Time",
    level: "Senior Level",
    salary: "$140/hr",
    location: "Delhi, India",
  },
  {
    id: 5,
    company: "Meta",
    logo: "https://logo.clearbit.com/meta.com",
    posted: "4 days ago",
    role: "UI Designer",
    type: "Remote",
    level: "Mid Level",
    salary: "$110/hr",
    location: "Pune, India",
  },
  {
    id: 6,
    company: "Adobe",
    logo: "https://logo.clearbit.com/adobe.com",
    posted: "6 days ago",
    role: "UX Researcher",
    type: "Full-Time",
    level: "Senior Level",
    salary: "$125/hr",
    location: "Noida, India",
  },
  {
    id: 7,
    company: "Spotify",
    logo: "https://logo.clearbit.com/spotify.com",
    posted: "1 week ago",
    role: "Product Designer",
    type: "Remote",
    level: "Mid Level",
    salary: "$105/hr",
    location: "Chennai, India",
  },
  {
    id: 8,
    company: "Airbnb",
    logo: "https://logo.clearbit.com/airbnb.com",
    posted: "2 days ago",
    role: "Visual Designer",
    type: "Contract",
    level: "Senior Level",
    salary: "$130/hr",
    location: "Gurgaon, India",
  },
  {
    id: 9,
    company: "Uber",
    logo: "https://logo.clearbit.com/uber.com",
    posted: "5 days ago",
    role: "Interaction Designer",
    type: "Full-Time",
    level: "Mid Level",
    salary: "$115/hr",
    location: "Bangalore, India",
  },
  {
    id: 10,
    company: "LinkedIn",
    logo: "https://logo.clearbit.com/linkedin.com",
    posted: "1 day ago",
    role: "Frontend Engineer",
    type: "Remote",
    level: "Senior Level",
    salary: "$135/hr",
    location: "Mumbai, India",
  },
  {
    id: 11,
    company: "Apple",
    logo: "https://logo.clearbit.com/apple.com",
    posted: "4 days ago",
    role: "UX Designer",
    type: "Full-Time",
    level: "Senior Level",
    salary: "$150/hr",
    location: "Hyderabad, India",
  },
  {
    id: 12,
    company: "Salesforce",
    logo: "https://logo.clearbit.com/salesforce.com",
    posted: "3 days ago",
    role: "Product Manager",
    type: "Full-Time",
    level: "Mid Level",
    salary: "$145/hr",
    location: "Pune, India",
  },
  {
    id: 13,
    company: "PayPal",
    logo: "https://logo.clearbit.com/paypal.com",
    posted: "6 days ago",
    role: "UI Engineer",
    type: "Remote",
    level: "Junior Level",
    salary: "$85/hr",
    location: "Delhi, India",
  },
  {
    id: 14,
    company: "Intel",
    logo: "https://logo.clearbit.com/intel.com",
    posted: "2 days ago",
    role: "Design System Engineer",
    type: "Full-Time",
    level: "Senior Level",
    salary: "$140/hr",
    location: "Noida, India",
  },
  {
    id: 15,
    company: "Oracle",
    logo: "https://logo.clearbit.com/oracle.com",
    posted: "1 week ago",
    role: "Senior Product Designer",
    type: "Remote",
    level: "Senior Level",
    salary: "$155/hr",
    location: "Bangalore, India",
  },
];

const App = () => {
  return (
    <div className='parent'>
      {users.map((user, idx) => {
        return <div key={idx}><Card company={user.company} role={user.role} logo={user.logo} posted={user.posted} type={user.type} level={user.level} salary={user.salary} location={user.location} /></div>
      })}
    </div>
  )
}

export default App